
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:929302374728:android:ffa7205a3ec59a5e1deb7d",
      #  firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        firebase_cli_token: "1//03zj120vWhhTHCgYIARAAGAMSNwF-L9IrIJ_AajQbUK2o6E-zbwhOzmTTEWoZPlqu6vM1ddbS5V3svbsF8uBgioyCZg2cCchTX2w",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "kamalhassan538@gmail.com",
        release_notes: "First Fastlane Firebase App Distribution",
  )
  end 
end
